name: Release with Maven

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up the JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          cache: 'maven'
      - name: Configure Git user
        run: |
          git config user.name "${{ github.event.head_commit.committer.name }}"
          git config user.email "${{ github.event.head_commit.committer.email }}"
      - name: Prepare release
        run: mvn -B release:prepare -DgithubOwner=nineinchnick -DgithubRepo=trino-plugin-archetype
      - name: Save version number in env
        run: |
          echo "VERSION=$(grep 'project.rel.pl.net.was\\:trino-plugin-archetype=' release.properties | cut -d'=' -f2)" >> $GITHUB_ENV

      - name: Publish JAR
        run: mvn -B release:perform -DgithubOwner=nineinchnick -DgithubRepo=trino-plugin-archetype -Darguments=-Dgpg.skip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run JReleaser
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_PROJECT_VERSION: ${{ env.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          setup-java: false

      - name: Upload test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test report ${{ github.job }}
          path: |
            **/surefire-reports/TEST-*.xml
            out/jreleaser/trace.log
            out/jreleaser/output.properties
          retention-days: 5
